base/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "base"   


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('home', views.home, name="home"),

    path('createProduct', views.createProduct, name="createProduct"),
    path('adminProduct', views.adminProduct, name="adminProduct"),
    path('deleteProduct/<str:pk>', views.deleteProduct, name="deleteProduct"),
    path('updateProduct/<str:pk>', views.updateProduct, name="updateProduct"),

    path('adminTopic', views.adminTopic, name="adminTopic"),
    path('updateTopic/<str:pk>', views.updateTopic, name="updateTopic"),
    path('deleteTopic/<str:pk>', views.deleteTopic, name="deleteTopic"),

    path('createBanner', views.createBanner, name="createBanner"),
    path('adminBanner', views.adminBanner, name="adminBanner"),
    path('updateBanner/<str:pk>', views.updateBanner, name="updateBanner"),
    path('deleteBanner/<str:pk>', views.deleteBanner, name="deleteBanner"),

    path('adminOrder', views.adminOrder, name="adminOrder"),
    path('viewOrderDetail/<str:pk>', views.viewOrderDetail, name="viewOrderDetail"),
    path('cancelOrder/<str:pk>', views.cancelOrder, name="cancelOrder"),
    path('updateOrder/<str:pk>', views.updateOrder, name="updateOrder"),

    path('createCupon', views.createCupon, name="createCupon"),
    path('adminCupon', views.adminCupon, name="adminCupon"),
    path('updateCupon/<str:pk>', views.updateCupon, name="updateCupon"),

    path('createEmail', views.createEmail, name="createEmail"),
    path('adminEmail', views.adminEmail, name="adminEmail"),
    path('sendEmail/<str:pk>', views.sendEmail, name="sendEmail"),

    path('updateShippingCost', views.updateShippingCost, name="updateShippingCost"),

    path('dashBoardLastOrder', views.dashBoardLastOrder, name="dashBoardLastOrder"),


    path('store/', include('store.urls', namespace='store')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cookies/', include('cookie_consent.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

from cookie_consent.views import CookieGroupAcceptView, CookieGroupDeclineView

app_name = "store"   


urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('cookiePolicy/', views.cookiePolicy, name="cookiePolicy"),
    path('usePolicy/', views.usePolicy, name="usePolicy"),

    path('userProfile', views.userProfile, name="userProfile"),
    path('personalInformation', views.personalInformation, name="personalInformation"),
    path('updateUserInfo/<str:pk>', views.updateUserInfo, name="updateUserInfo"),
    path('securityInformation', views.securityInformation, name="securityInformation"),
    path('updatePassword/<str:pk>', views.updatePassword, name="updatePassword"),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('deleteUser/<str:pk>', views.deleteUser, name="deleteUser"),
    
    path('viewOrder', views.viewOrder, name="viewOrder"),
    path('viewOrderDetail/<str:pk>', views.viewOrderDetail, name="viewOrderDetail"),

    path('userAddress', views.userAddress, name="userAddress"),
    path('createAddress', views.createAddress, name="createAddress"),
    path('deleteAddress/<str:pk>', views.deleteAddress, name="deleteAddress"),

    path('', views.home, name="home"),
    path('aboutUs', views.aboutUs, name="aboutUs"),
    path('shopDetail/<str:pk>', views.shopDetail, name="shopDetail"),
    path('store', views.store, name="store"),
    path('addCart/<str:pk>', views.addCart, name="addCart"),
    path('addCartDetail/<str:pk>', views.addCartDetail, name="addCartDetail"),
    path('viewCart', views.viewCart, name="viewCart"),
    path('checkout', views.checkout, name="checkout"),
    path('createOrder/<str:pk>', views.createOrder, name="createOrder"),
    path('cancelStoreOrder/<str:pk>', views.cancelStoreOrder, name="cancelStoreOrder"),

    path('validateCupon', views.validateCupon, name="validateCupon"),
    path('removeCupon', views.removeCupon, name="removeCupon"),

    path('updateCart', views.updateCart, name='updateCart'),
    path('deleteCart/<str:pk>', views.deleteCart, name='deleteCart'),
]

store/models.py
from django.db import models

# Create your models here.

store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from base.models import User

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'lastName', 'phone', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['name', 'lastName', 'phone', 'email']

store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.auth.hashers import check_password
from django.views.decorators.cache import never_cache
from django.utils import timezone

from django.db.models import Q, F
from base.models import Product, Topic, Banner, User, Cart, UserAddress, PurchaseOrder, PurchaseOrderItem, ShippingCost, Cupon

from .helpers import ProductCart, CuponAdmin

from cookie_consent.views import CookieGroupAcceptView

from store.forms import UserForm, MyUserCreationForm

from datetime import timedelta
import string
import random
import json

def cookiePolicy(request):
    return render(request, 'store/cookiePolicy.html')

def usePolicy(request):
    return render(request, 'store/usePolicy.html')
def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('store:home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.error(request, 'El correo electrónico no está registrado')
            return redirect('store:login')

        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('store:home')
        else:
            messages.error(request, 'El correo electrónico o la contraseña son incorrectos')

    context = {'page': page, 'messages': messages.get_messages(request)}
    return render(request, 'store/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('store:home')

def registerPage(request):
    page = 'register'
    topics = Topic.objects.all()[:3]

    if request.method == 'POST':
        name = request.POST.get('name').capitalize()
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        confirmPassword = request.POST.get('confirmPassword')
        acceptUsePolicy = request.POST.get('usePolicy')
        acceptCommPolicy = request.POST.get('commPolicy')

        # Check if the user already exists
        if User.objects.filter(email=email).exists():
            messages.error(request, 'El correo electronico ya está en uso.')
            return redirect('store:register')

        # Verify if passwords match
        if password != confirmPassword:
            messages.error(request, 'Las contraseñas no coinciden.')
            return redirect('store:register')

        if not acceptUsePolicy:
            messages.error(request, 'Es necesario que aceptes las políticas de privacidad y condiciones de uso para registrarte.')
            return redirect('store:register')

        # Create user
        user = User.objects.create_user(username=email, email=email, password=password, name=name)
        if acceptCommPolicy:
            user.commPolicy = True
        user.save()

        # Authenticate and login the user
        user = authenticate(request, username=email, password=password)

        # Envía el correo electrónico con la nueva contraseña utilizando la plantilla HTML
        subject = '¡Bienvenido a Edjo!'
        from_email = 'danielfeperezgalindo@gmail.com'  # Coloca aquí tu dirección de correo Gmail
        recipient_list = [email]

        cuponName = CuponAdmin.FirstOrderCupon(user)


        # Renderiza la plantilla HTML con los datos necesarios
        html_message = render_to_string('email/cuponFirstOrder.html', {'cuponName': cuponName.cupon, 'value': cuponName.value, 'topics': topics, 'user': user})
        plain_message = strip_tags(html_message)

        # Crea el objeto EmailMultiAlternatives para enviar el correo con contenido HTML y texto plano
        msg = EmailMultiAlternatives(subject, plain_message, from_email, recipient_list)
        msg.attach_alternative(html_message, "text/html")
        msg.send()


        if user is not None:
            login(request, user)
            return redirect('store:home')

    context = {'page': page, 'messages': messages.get_messages(request)}
    return render(request, 'store/login_register.html',context)

def generateRandomPassword(length=10):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))


def resetPassword(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            newPassword = generateRandomPassword()
            user.set_password(newPassword)
            user.save()

            # Envía el correo electrónico con la nueva contraseña utilizando la plantilla HTML
            subject = 'Solicitud de cambio de contraseña'
            from_email = 'danielfeperezgalindo@gmail.com'  # Coloca aquí tu dirección de correo Gmail
            recipient_list = [email]

            # Renderiza la plantilla HTML con los datos necesarios
            html_message = render_to_string('email/resetPasswordEmail.html', {'newPassword': newPassword})
            plain_message = strip_tags(html_message)

            # Crea el objeto EmailMultiAlternatives para enviar el correo con contenido HTML y texto plano
            msg = EmailMultiAlternatives(subject, plain_message, from_email, recipient_list)
            msg.attach_alternative(html_message, "text/html")
            msg.send()

            return redirect('store:login')
        except User.DoesNotExist:
            messages.error(request, 'El correo electronico no esta registrado.')
            return redirect('store:resetPassword')

    return render(request, 'store/resetPassword.html')

def home(request):
    topics = Topic.objects.all()
    banners = Banner.objects.all()
    products = Product.objects.order_by('-discount')

    if request.user.is_authenticated:
        cart, create = Cart.objects.get_or_create(user=request.user)
        numberProductsCart = ProductCart.numberProducts(cart)

        context = {
            'topics': topics,
            'banners': banners,
            'numberProductsCart': numberProductsCart,
            'products': products}

    else:
        context = {
            'topics': topics,
            'banners': banners,
            'products': products}

    # Iterate through topics and handle instances with no image assigned
    for topic in topics:
        if topic.image and topic.image.file:
            topic.image_url = topic.image.url
        else:
            topic.image_url = None

    return render(request, 'store/home.html', context)


def shopDetail(request,pk):
    product = Product.objects.get(id=pk)
    products = Product.objects.all()
    topics = Topic.objects.all()

    if request.user.is_authenticated:
        cart, create = Cart.objects.get_or_create(user=request.user)
        numberProductsCart = ProductCart.numberProducts(cart)

        context = {
            'products':products,
            'product':product,
            'topics':topics,
            'numberProductsCart':numberProductsCart
            }
    else:
        context = {
            'products': products,
            'product': product,
            'topics': topics
        }

    return render(request,'store/shopDetail.html', context)

def store(request):
    query = request.GET.get('q') if request.GET.get('q') != None else ''
    query_max_price = request.GET.get('q_max_price') if request.GET.get('q_max_price') != None else ''
    query_min_price = request.GET.get('q_min_price') if request.GET.get('q_min_price') != None else ''
    query_min_discount = request.GET.get('q_min_discount') if request.GET.get('q_min_discount') != None else ''
    order_by = request.GET.get('order_by', 'default_orders') 
    topics = Topic.objects.all()
    if request.user.is_authenticated:
        cart, create = Cart.objects.get_or_create(user=request.user)
        numberProductsCart = ProductCart.numberProducts(cart)

    if query_max_price != '' and query_min_price != '': 
        products = Product.objects.filter(
            Q(price__gte=query_min_price) &
            Q(price__lte=query_max_price))
    elif query_max_price != '': 
        products = Product.objects.filter(
            Q(price__lte=query_max_price)
            )
    elif query_min_discount != '': 
        products = Product.objects.filter(
            Q(discount__gte=query_min_discount)
            )
        print('hpt')
    elif query:
        products = Product.objects.filter(
            Q(topic__name__icontains = query)|
            Q(name__icontains= query)|
            Q(bio__icontains= query)
        )
    else: 
        products = Product.objects.all().order_by('-discount')
    
    if order_by=="priceDiscount":
        products = products.order_by('priceDiscount')
    elif order_by=="-priceDiscount":
        products = products.order_by('-priceDiscount')
    elif order_by=="name":
        products = products.order_by('name')
    elif order_by=="-name":
        products = products.order_by('-name')
    elif order_by=="discount":
        products = products.order_by('-discount')
    elif order_by=="-discount":
        products = products.order_by('discount')
    
    paginator = Paginator(products, 9)
    page_number = request.GET.get('page')

store/templates/store/CookiePolicy.html
{% extends 'store/main.html' %}
{% load humanize %}

{% block content %}
    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Cómo Utilizamos las Cookies para Mejorar tu Experiencia en Edjo</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->
    <!-- ***** About Area Starts ***** -->
    <div class="about-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="right-content">
                        <h4>¿Qué son las cookies?</h4>
                        <div class="quote">
                            <p>Las cookies son pequeños archivos de datos que los sitios web y las aplicaciones almacenan en tu dispositivo cuando interactúas con ellos. Estos archivos contienen información que se utiliza para rastrear y almacenar detalles sobre tus interacciones en línea. Las cookies son una parte fundamental de la experiencia de navegación en la web moderna y cumplen diversas funciones esenciales para mejorar la usabilidad de los sitios web y proporcionar servicios personalizados a los usuarios.</p>
                            <p>Cuando visitas un sitio web, este puede enviar una cookie a tu navegador web (como Chrome, Firefox o Safari). Esta cookie se almacena en tu dispositivo (como una computadora, un teléfono inteligente o una tableta) y se asocia con ese sitio web en particular. A partir de ese momento, cada vez que vuelvas a ese sitio web, tu navegador enviará la cookie de vuelta al servidor del sitio web. Esto permite que el sitio web recuerde información específica sobre tu visita anterior, como tus preferencias de configuración, tu historial de navegación y, en algunos casos, datos de inicio de sesión.</p>
                        </div>
                    </div>
                    <div class="right-content pt-5 pb-5">
                        <h4>¿Cómo utilizamos las cookies?</h4>
                        <div class="quote">
                            <p class="pb-1"> Utilizamos cookies para diversas finalidades, que incluyen:</p>
                            <p><strong>1. Sesiones de Usuario:</strong> Las cookies también se utilizan para administrar tus sesiones de usuario. Cuando inicias sesión en tu cuenta, una cookie se crea para mantener tu sesión activa de manera segura. Esto significa que no tendrás que volver a iniciar sesión cada vez que accedas a una página diferente en nuestro sitio.</p>

                            <p><strong>2. Analítica Web:</strong> Utilizamos cookies de analítica web para comprender cómo los visitantes interactúan con nuestro sitio. Esto nos permite recopilar información sobre las páginas que visitas, el tiempo que pasas en cada página y las acciones que realizas. Estos datos se utilizan para mejorar continuamente nuestro sitio y ofrecerte un contenido y una navegación más relevantes.</p>

                            <p><strong>3. Publicidad Personalizada:</strong> Las cookies de publicidad nos ayudan a mostrarte anuncios que son relevantes para ti en función de tu historial de navegación y compras anteriores. Esto no solo te brinda ofertas y productos que puedan interesarte, sino que también ayuda a mantener nuestro sitio web gratuito para todos los usuarios.</p>

                            <p><strong>4. Seguridad:</strong> Las cookies son esenciales para garantizar la seguridad de tu cuenta y de todas las transacciones en línea que realices en nuestro sitio. Ayudan a prevenir actividades fraudulentas y a proteger tus datos personales.</p>

                            <p><strong>5. Almacenamiento de Información:</strong> Cuando visitas nuestro sitio, las cookies permiten que guardemos cierta información en tu dispositivo. Esta información puede incluir tus preferencias de idioma, elementos en tu carrito de compras y otros datos relevantes que hacen que tu experiencia sea más personalizada.</p>
                        </div>
                    </div>
                    <div class="right-content">
                        <h4>¿Cómo puedes gestionar las cookies?</h4>
                        <div class="quote">
                            <p>Si decides cancelar las cookies en cualquier momento, puedes hacerlo desde la configuración de tu navegador. Sin embargo, ten en cuenta que si desactivas las cookies, es posible que no puedas utilizar todas las características de la tienda, incluyendo la capacidad para registrarte e identificarte como usuario.</p>
                            <p>Para obtener más detalles sobre nuestras prácticas de privacidad y cómo utilizamos tus datos personales, consulta nuestra <a href="{% url 'store:usePolicy' %}">Política de Privacidad</a>.</p>
                            <p>Gracias por elegir Edjo para tus compras en línea. ¡Esperamos que tengas una experiencia de compra increíble!</p>
                            <p>Si tienes alguna pregunta o inquietud sobre nuestra política de cookies o cualquier otro aspecto de nuestro sitio web, no dudes en ponerte en contacto con nuestro equipo de atención al cliente en Example@example.com.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

store/templates/store/home.html
{% extends 'store/main.html' %}

{% block content %}

    {% include 'store/bannerTopicArea.html' %}

    {% include 'store/productInfo.html' %}


{% endblock %}

store/templates/store/viewCart.html
{% extends 'store/main.html' %}
{% load humanize %}

{% block content %}
    <!-- Cart Start -->

        <!-- ***** Main Banner Area Start ***** -->
        <div class="page-heading" id="top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="inner-content">
                            <h2>Carrito de compra</h2>
                            <span>Awesome &amp; Creative HTML CSS layout by TemplateMo</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Main Banner Area End ***** -->


        <div class="container-fluid pt-5">
            <div class="row px-xl-5">
                <div class="col-lg-8 table-responsive mb-5 products-desktop">
                    <table class="table table-cart table-bordered no-vertical-border text-center mb-0" id="CartTable">
                        <thead class="bg-secondary text-dark">
                            <tr>
                                <th class="d-none">#</th>
                                <th>Imagen</th>
                                <th>Productos</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th>Remover</th>
                            </tr>
                        </thead>
                        <tbody class="align-middle">
                            {% for product in productCart %}
                            <tr class="cart-row">
                                <td  class="align-middle d-none" id="{{ product.id }}">{{ product.id }}</td>
                                <td class="align-middle" id="price_{{ product.id }}"><img src="{{product.image_url}}" alt="{{ product.name }}" style="width: 75px;"></td>
                                <td class="align-middle">
                                    {{ product.name }}<br>
                                {% if product.stock <= 10  %}
                                              <div class="bg-pink text-danger d-flex justify-content-center">
                                                  ({{product.stock}} Disponibles)
                                              </div>
                                {% else %}
                                    ({{product.stock}} Disponibles)
                                {% endif %}

                                </td>
                                <td class="align-middle" id="price_{{ product.id }}">${{ product.price|intcomma }}</td>
                                <td class="align-middle">
                                    <form method="POST" action="">
                                        {% csrf_token %}
                                        <div class="quantity-content quantity-content-cart">
                                            <div class="right-content">
                                                <div class="quantity buttons_added">
                                                    <input type="button" value="-" class="minus-cart"><input type="number" step="1" min="1" max="" name="quantity" value="{{ product.quantity }}" title="Qty" class="input-text qty text" size="4" pattern="" inputmode="" readonly><input type="button" value="+" class="plus-cart">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                                <td class="align-middle" id="total_price_{{ product.id }}"> ${{ product.total|intcomma }} </td>

                                <td class="align-middle">
                                    <form action="{% url 'store:deleteCart' pk=product.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button>
                                    </form>
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-8 table-responsive mb-5 products-mobile">
                {% for product in productCart %}
                <div class="container container-mobile pt-4">
                    <div class="row pb-4">
                        <div class="col-6">
                            <img src="{{product.image.url}}" alt="{{ product.name }}" style="width: 100%;">
                        </div>
                        <div class="col-6">
                            <div class="mobile-product-name">
                                <h6>{{ product.name }}</h6>
                                <div>
                                    <form action="{% url 'store:deleteCart' pk=product.id %}" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-lg pl-1 "><i class="fa fa-trash"></i></button>
                                    </form>
                                </div>
                            </div>
                            <div class="price-mobile">
                                <p class="align-middle" id="price_{{ product.id }}">${{ product.price|intcomma}}</p>
                            </div>
                            <div>
                                <table class="table table-cart table-cart-mobile table-borderless mb-0" id="CartTable">
                                    <tbody class="align-middle">
                                        <tr>
                                            <td  class="align-middle  d-none" id="{{ product.id }}">{{ product.id }}</td>
                                            <td class="pl-0">
                                                <form method="POST" action="">
                                                    <div class="quantity-content quantity-content-cart quantity-content-cart-mobile">
                                                            <div class="quantity buttons_added">
                                                                <input type="button" value="-" class="minus-cart"><input type="number" step="1" min="1" max="" name="quantity" value="{{ product.quantity }}" title="Qty" class="input-text qty text" size="4" pattern="" inputmode="" readonly><input type="button" value="+" class="plus-cart">
                                                            </div>
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div>
                                <p id="total_price_{{ product.id }}_mobile"> ${{ product.total|intcomma }} </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                </div>
                <div class="col-lg-4">

                    <div class="card border-secondary mb-5">
                        <div class="card-header bg-secondary border-0">
                            <h4 class="font-weight-semi-bold m-0">Total en el Carro</h4>
                        </div>
                        <div class="card-body">
                            <div class="d-flex justify-content-between mb-3 pt-1">
                                <h6 class="font-weight-medium">Subtotal</h6>
                                <h6 class="font-weight-medium" id="subtotal">${{ subTotal|intcomma }}</h6>
                            </div>
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Costo de Envío</h6>
                                <h6 class="font-weight-medium">${{ cost|intcomma }}</h6>
                            </div>
                        </div>
                        <div class="card-footer border-secondary bg-transparent">
                            <div class="d-flex justify-content-between mt-2">
                                <h5 class="font-weight-bold">Total</h5>
                                <h5 class="font-weight-bold" id="total_price">${{ total|intcomma }}</h5>
                            </div>
                            {% if productCart %}
                            <a href="{%  url 'store:checkout' %}"><button type="button"   class="btn btn-block btn-primary my-3 py-3">Continuar con la Compra</button></a>
                            {% else %}
                                <div class="error-messages text-left">
                                  <p style="color:red">*Debes agregar productos al carrito<br></p>
                             </div>
                                <a href="{%  url 'store:checkout' %}"><button type="button"   class="btn btn-block btn-primary my-3 py-3" disabled>Continuar con la Compra</button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!-- Cart End -->
{% endblock %}