base/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "base"   


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('home', views.home, name="home"),

    path('createProduct', views.createProduct, name="createProduct"),
    path('adminProduct', views.adminProduct, name="adminProduct"),
    path('deleteProduct/<str:pk>', views.deleteProduct, name="deleteProduct"),
    path('updateProduct/<str:pk>', views.updateProduct, name="updateProduct"),

    path('adminTopic', views.adminTopic, name="adminTopic"),
    path('updateTopic/<str:pk>', views.updateTopic, name="updateTopic"),
    path('deleteTopic/<str:pk>', views.deleteTopic, name="deleteTopic"),

    path('createBanner', views.createBanner, name="createBanner"),
    path('adminBanner', views.adminBanner, name="adminBanner"),
    path('updateBanner/<str:pk>', views.updateBanner, name="updateBanner"),
    path('deleteBanner/<str:pk>', views.deleteBanner, name="deleteBanner"),

    path('adminOrder', views.adminOrder, name="adminOrder"),
    path('viewOrderDetail/<str:pk>', views.viewOrderDetail, name="viewOrderDetail"),
    path('cancelOrder/<str:pk>', views.cancelOrder, name="cancelOrder"),
    path('updateOrder/<str:pk>', views.updateOrder, name="updateOrder"),

    path('createCupon', views.createCupon, name="createCupon"),
    path('adminCupon', views.adminCupon, name="adminCupon"),
    path('updateCupon/<str:pk>', views.updateCupon, name="updateCupon"),

    path('createEmail', views.createEmail, name="createEmail"),
    path('adminEmail', views.adminEmail, name="adminEmail"),
    path('sendEmail/<str:pk>', views.sendEmail, name="sendEmail"),

    path('updateShippingCost', views.updateShippingCost, name="updateShippingCost"),

    path('dashBoardLastOrder', views.dashBoardLastOrder, name="dashBoardLastOrder"),


    path('store/', include('store.urls', namespace='store')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cookies/', include('cookie_consent.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

from cookie_consent.views import CookieGroupAcceptView, CookieGroupDeclineView

app_name = "store"   


urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('cookiePolicy/', views.cookiePolicy, name="cookiePolicy"),
    path('usePolicy/', views.usePolicy, name="usePolicy"),

    path('userProfile', views.userProfile, name="userProfile"),
    path('personalInformation', views.personalInformation, name="personalInformation"),
    path('updateUserInfo/<str:pk>', views.updateUserInfo, name="updateUserInfo"),
    path('securityInformation', views.securityInformation, name="securityInformation"),
    path('updatePassword/<str:pk>', views.updatePassword, name="updatePassword"),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('deleteUser/<str:pk>', views.deleteUser, name="deleteUser"),
    
    path('viewOrder', views.viewOrder, name="viewOrder"),
    path('viewOrderDetail/<str:pk>', views.viewOrderDetail, name="viewOrderDetail"),

    path('userAddress', views.userAddress, name="userAddress"),
    path('createAddress', views.createAddress, name="createAddress"),
    path('deleteAddress/<str:pk>', views.deleteAddress, name="deleteAddress"),

    path('', views.home, name="home"),
    path('aboutUs', views.aboutUs, name="aboutUs"),
    path('shopDetail/<str:pk>', views.shopDetail, name="shopDetail"),
    path('store', views.store, name="store"),
    path('addCart/<str:pk>', views.addCart, name="addCart"),
    path('addCartDetail/<str:pk>', views.addCartDetail, name="addCartDetail"),
    path('viewCart', views.viewCart, name="viewCart"),
    path('checkout', views.checkout, name="checkout"),
    path('createOrder/<str:pk>', views.createOrder, name="createOrder"),
    path('cancelStoreOrder/<str:pk>', views.cancelStoreOrder, name="cancelStoreOrder"),

    path('validateCupon', views.validateCupon, name="validateCupon"),
    path('removeCupon', views.removeCupon, name="removeCupon"),

    path('updateCart', views.updateCart, name='updateCart'),
    path('deleteCart/<str:pk>', views.deleteCart, name='deleteCart'),
]

templates/footer.html
<!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
                </a>
                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Cra 11 #18-68, Honda-Tolima</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>catali1982@hotmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+57 3144009545</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        
                        <div class="d-flex flex-column justify-content-start">
                            
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4"></h5>
                        <div class="d-flex flex-column justify-content-start">
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                    Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

templates/navbar.html
{% load static %}

<header class="header header--loggedIn">
        <!-- Topbar Start -->
        <div class="container-fluid">
            <div class="row align-items-center py-3 px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <a href="{% url 'store:home' %}" class="text-decoration-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                </div>
                <div class="col-lg-6 col-6 text-left">
                    <form action="{% url 'store:store' %}" method="GET" >
                        {% csrf_token %}
                        <div class="input-group">
                            <input name="q" type="text" class="form-control" placeholder="Search for products">
                            <div class="input-group-append">
                                <span class="input-group-text bg-transparent text-primary">
                                    <i class="fa fa-search"></i>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Topbar End -->
    
    
        <!-- Navbar Start -->
        <div class="container-fluid mb-5">
            <div class="row border-top px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                        <h6 class="m-0">Categories</h6>
                        <i class="fa fa-angle-down text-dark"></i>
                    </a>
                    <nav class="collapse navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                        <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                            {% for topic in topics %}
                                <a href="{% url 'store:store' %}?q={{topic.name}}" class="nav-item nav-link">{{topic.name}}</a>
                            {% endfor %}
                        </div>
                    </nav>
                </div>
                <div class="col-lg-9">
                    <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                        <a href="" class="text-decoration-none d-block d-lg-none">
                            <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                        </a>
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                            <div class="navbar-nav mr-auto py-0">
                                <a href="{% url 'store:home' %}" class="nav-item nav-link active">Home</a>
                                <a href="{% url 'store:store' %}" class="nav-item nav-link">Shop</a>
                                <a href="detail.html" class="nav-item nav-link">Shop Detail</a>
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                                    <div class="dropdown-menu rounded-0 m-0">
                                        <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                        <a href="checkout.html" class="dropdown-item">Checkout</a>
                                    </div>
                                </div>
                                <a href="contact.html" class="nav-item nav-link">Contact</a>
                            </div>

                            {% if request.user.is_authenticated %}
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{request.user.name}}</a>
                                    <div class="dropdown-menu rounded-0 m-0">
                                        <a href="cart.html" class="dropdown-item">Perfil</a>
                                        <a href="{% url 'store:logout' %}" class="dropdown-item">Cerrar Sesion</a>
                                    </div>
                                    
                                </div>
                                <a href="" class="nav-item nav-link">Mis Compras</a>
                                <div>
                                    <a href="{% url 'store:viewCart' %}" class="btn border">
                                        <i class="fas fa-shopping-cart text-primary"></i>
                                        <span id="number_products" class="badge">{{ numberProductsCart }}</span>
                                    </a>
                                </div>
                            {% else %}
                                <!-- Not Logged In -->
                                <div class="navbar-nav ml-auto py-0">
                                    <a href="{% url 'store:login' %}" class="nav-item nav-link">Iniciar Sesion</a>
                                    <a href="{% url 'store:register' %}" class="nav-item nav-link">Registrarse</a>
                                </div>

                            {% endif %}
                            
                        </div>
                    </nav>

                    
                    {% if request.resolver_match.url_name == 'home' %}
                        <div id="header-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for banner in banners %}
                                    {% if banner == banners.0 %}
                                        <div class="carousel-item active" style="height: 410px;">
                                    {% else %}
                                        <div class="carousel-item" style="height: 410px;">
                                    {% endif %}
                                        {% if banner.image %}
                                            <img class="img-fluid" src="{{banner.image.url}}" alt="Image">
                                        {% endif %}
                                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                            <div class="p-3" style="max-width: 700px;">
                                                <h4 class="text-light text-uppercase font-weight-medium mb-3">{{banner.message}}</h4>
                                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">{{banner.title}}</h3>

                                                {% if banner.type == 'Categoria' %}
                                                <a href="{% url 'store:store' %}?q={{banner.topic}}" class="btn btn-light py-2 px-3">Shop Now</a>
                                                {% elif banner.type == 'Precio Maximo' %}
                                                <a href="{% url 'store:store' %}?q_max_price={{banner.maxPrice}}" class="btn btn-light py-2 px-3">Shop Now</a>
                                                {% elif banner.type == 'Rango de Precio' %}
                                                <a href="{% url 'store:store' %}?q_max_price={{banner.maxPrice}}&q_min_price={{banner.minPrice}}" class="btn btn-light py-2 px-3">Shop Now</a>
                                                {% elif banner.type == 'Descuento Minimo' %}
                                                <a href="{% url 'store:store' %}?q_min_discount={{banner.minDiscount}}" class="btn btn-light py-2 px-3">Shop Now</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                                <div class="btn btn-dark" style="width: 45px; height: 45px;">
                                    <span class="carousel-control-prev-icon mb-n2"></span>
                                </div>
                            </a>
                            <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                                <div class="btn btn-dark" style="width: 45px; height: 45px;">
                                    <span class="carousel-control-next-icon mb-n2"></span>
                                </div>
                            </a>
                        </div>

                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Navbar End -->
        <div class="modal fade " id="modalBoot" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-bottom-right" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Se agrego el producto: </h5>
              </div>
              <div class="modal-body d-flex align-items-center justify-content-center">
                  <img src="" alt="" class="rounded">
                <p class="m-0 pl-2"></p>
              </div>
            </div>
          </div>
        </div>
    
</header>